<?php

namespace CampBundle\Repository;

/**
 * blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogRepository extends \Doctrine\ORM\EntityRepository
{

    public function countDQL()
    {
        $qb=$this->getEntityManager()
            ->createQuery("SELECT  COUNT (e) as nb 
                            FROM CampBundle:blog e  ");
        return $qb->getResult();
    }

    public function counntDQL($i)
    {
        $qb=$this->getEntityManager()
            ->createQuery("SELECT COUNT (e) FROM CampBundle:blog e  where e.refuge=:id")
           ->setParameter('id',$i);

         return $qb->getResult();


    }

    public function coountDQL($i)
    {
        $qb=$this->getEntityManager()
            ->createQuery("SELECT u.nom
                            FROM CampBundle:refuge u where u.id =:id")
            ->setParameter('id',$i);

        return $qb->getResult();

    }


}
