<?php

namespace CampBundle\Repository;

/**
 * likePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likePostRepository extends \Doctrine\ORM\EntityRepository
{
}
