<?php

namespace CampBundle\Repository;

/**
 * migrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class migrantRepository extends \Doctrine\ORM\EntityRepository
{
    public function counntDQL($i)
    {
        $qb=$this->getEntityManager()
            ->createQuery("SELECT COUNT (e) FROM CampBundle:migrant e  where e.refuge=:id")
            ->setParameter('id',$i);

        return $qb->getResult();


    }
}
