<?php

namespace CampBundle\Repository;

/**
 * refugeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class refugeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM CampBundle:refuge e
                WHERE e.nom LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function OrderByPour(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT(e)
                FROM CampBundle:refuge e
                 '
            )
            ->getResult();
    }

    public function OrderBy(){

        $qb=$this->CreateQueryBuilder('s');

        $qb->orderBy('s.pour', 'DESC')->setMaxResults(1);
        return $qb->getQuery()->getResult();


    }
}
