<?php

namespace CampBundle\Repository;

/**
 * refugeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class refugeRepository extends \Doctrine\ORM\EntityRepository
{
}
