<?php

namespace ActionBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;

/**
 * PostcommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByid($id)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT a
                FROM ActionBundle:Action
                a WHERE a.id =:id"
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();


    }
    public function findActionByid($id)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM ActionBundle:Action
                p WHERE p.id =:id"
                )
                ->setParameter('id', $id)
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }
    }
}
